"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/client";
type Entry = { id: string; source: "Add Lead" | "Workload"; name: string; address: string; phone: string; email: string; scope: string[]; rgu: number | null; converted: boolean; convertedAt: string | null; salesCount: number; telusSims: number; koodoSims: number };
export function OpportunitiesClient() {
  const [entries,setEntries]=useState<Entry[]>([]);
  useEffect(()=>{const load=async()=>{const supabase=createClient();const [{data:leads},{data:jobs}]=await Promise.all([supabase.from("leads").select("*"),supabase.from("jobs").select("*")]);const a:Entry[]=(leads||[]).map((lead)=>({id:lead.id,source:"Add Lead",name:`${lead.first_name||""} ${lead.last_name||""}`.trim()||lead.company||"Unnamed lead",address:lead.address||"",phone:lead.phone||"",email:lead.email||"",scope:lead.sale_scope||[],rgu:lead.possible_rgu_sale,converted:lead.status==="converted",convertedAt:lead.converted_at||null,salesCount:Number(lead.sales_count||0),telusSims:Number(lead.telus_sims_sold||0),koodoSims:Number(lead.koodo_sims_sold||0)}));const b:Entry[]=(jobs||[]).map((job)=>{const data=(job.lead_data||{}) as Record<string,unknown>;return{id:job.id,source:"Workload",name:job.customer_name||"Unnamed customer",address:job.address||"",phone:String(data.phone||""),email:String(data.email||""),scope:Array.isArray(data.sale_scope)?data.sale_scope as string[]:[],rgu:typeof data.possible_rgu_sale==="number"?data.possible_rgu_sale:null,converted:job.sale_done_by_me===true,convertedAt:job.sale_converted_at||null,salesCount:Number(job.sales_count||0),telusSims:Number(job.telus_sims_sold||0),koodoSims:Number(job.koodo_sims_sold||0)};});setEntries([...a,...b]);};const frame=requestAnimationFrame(load);const interval=window.setInterval(load,15000);window.addEventListener("focus",load);return()=>{cancelAnimationFrame(frame);window.clearInterval(interval);window.removeEventListener("focus",load);};},[]);
  const sections=useMemo(()=>[{title:"Sales I have done",items:entries.filter((e)=>e.converted)},{title:"Not sold but possible",items:entries.filter((e)=>!e.converted)}],[entries]);
  return <main className="min-h-screen bg-background p-5 text-foreground sm:p-8"><div className="mx-auto max-w-6xl"><Link href="/" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4"/> Dashboard</Link><Badge className="border-primary/30 bg-primary/10 text-primary">COMBINED SALES LIST</Badge><h1 className="mt-3 text-3xl font-semibold">Sales opportunities</h1><p className="mt-2 text-sm text-muted-foreground">Combined from Add Lead and Workload while keeping both source lists separate.</p><div className="mt-6 grid gap-6 lg:grid-cols-2">{sections.map((section)=><Card key={section.title}><CardHeader><CardTitle>{section.title} ({section.items.length})</CardTitle></CardHeader><CardContent className="space-y-3">{section.items.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No entries in this section.</p>:section.items.map((entry)=><div key={`${entry.source}-${entry.id}`} className="rounded-lg border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{entry.name}</p><p className="mt-1 break-words text-sm text-muted-foreground">{entry.address||entry.email||entry.phone||"No contact details"}</p></div><Badge className="shrink-0 bg-primary/10 text-primary">{entry.source}</Badge></div><p className="mt-3 text-xs text-muted-foreground">{entry.converted ? "What sold" : "Possible sale"}: {entry.scope.join(", ")||"Not listed"} · Possible RGU: {entry.rgu||"—"}{entry.converted ? ` · Sale date: ${entry.convertedAt?.slice(0,10)||"Not set"} · Number sold: ${entry.salesCount} · TELUS SIMs: ${entry.telusSims} · Koodo SIMs: ${entry.koodoSims}` : ""}</p></div>)}</CardContent></Card>)}</div></div></main>;
}
