"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/client";
const PRODUCTS=["Fibre internet","Copper internet","Optik TV","Home phone","Security","Mobility"];
type Lead={id:string;first_name:string;last_name:string;company:string;status:string;sale_scope:string[];current_services:string[];next_follow_up_at:string|null};
export function ActiveOpportunities(){const[leads,setLeads]=useState<Lead[]>([]);useEffect(()=>{const load=async()=>{const{data}=await createClient().from("leads").select("id,first_name,last_name,company,status,sale_scope,current_services,next_follow_up_at").not("status","in",'("converted","unqualified")').order("updated_at",{ascending:false}).limit(8);setLeads((data||[])as Lead[]);};const frame=requestAnimationFrame(load);const interval=window.setInterval(load,15000);window.addEventListener("focus",load);return()=>{cancelAnimationFrame(frame);window.clearInterval(interval);window.removeEventListener("focus",load);};},[]);return <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Active opportunities</CardTitle><p className="mt-1 text-sm text-muted-foreground">Live scope and products each customer does not have.</p></div><Link href="/opportunities"><Button variant="ghost" size="sm">View all <ArrowUpRight/></Button></Link></CardHeader><CardContent><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="pb-3">Customer</th><th className="pb-3">Stage</th><th className="pb-3">Scope of sale</th><th className="pb-3">Products customer does not have</th><th className="pb-3 text-right">Follow-up</th></tr></thead><tbody>{leads.length?leads.map((lead)=>{const missing=PRODUCTS.filter((product)=>!lead.current_services?.includes(product));return <tr key={lead.id} className="border-b border-border/60 last:border-0"><td className="py-4"><p className="font-medium">{`${lead.first_name||""} ${lead.last_name||""}`.trim()||lead.company||"Unnamed customer"}</p><p className="text-xs text-muted-foreground">{lead.company||"Customer lead"}</p></td><td><Badge className="border-primary/20 bg-primary/10 capitalize text-primary">{lead.status}</Badge></td><td className="text-xs">{lead.sale_scope?.join(", ")||"Not selected"}</td><td className="text-xs text-muted-foreground">{missing.join(", ")||"Customer has all products"}</td><td className="text-right text-xs text-muted-foreground">{lead.next_follow_up_at?.slice(0,10)||"Not set"}</td></tr>}):<tr><td colSpan={5} className="py-10 text-center text-muted-foreground">No active opportunities yet.</td></tr>}</tbody></table></div></CardContent></Card>;}
