"use client";
import { useEffect, useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/client";
type Period="daily"|"weekly"|"monthly"|"yearly";
type Lead={id:string;converted_at:string|null;sale_scope:string[];telus_sims_sold:number;koodo_sims_sold:number};
type Job={id:string;lead_id:string|null;sale_converted_at:string|null;lead_data:{sale_scope?:string[]}|null;telus_sims_sold:number;koodo_sims_sold:number};
function start(period:Period){const date=new Date();date.setHours(0,0,0,0);if(period==="weekly"){const day=date.getDay()||7;date.setDate(date.getDate()-day+1);}if(period==="monthly")date.setDate(1);if(period==="yearly")date.setMonth(0,1);return date.getTime();}
export function ProductSalesTracker(){const[period,setPeriod]=useState<Period>("monthly");const[leads,setLeads]=useState<Lead[]>([]);const[jobs,setJobs]=useState<Job[]>([]);useEffect(()=>{const load=async()=>{const supabase=createClient();const[{data:a},{data:b}]=await Promise.all([supabase.from("leads").select("id,converted_at,sale_scope,telus_sims_sold,koodo_sims_sold"),supabase.from("jobs").select("id,lead_id,sale_converted_at,lead_data,telus_sims_sold,koodo_sims_sold")]);setLeads((a||[])as Lead[]);setJobs((b||[])as Job[]);};const frame=requestAnimationFrame(load);const interval=window.setInterval(load,15000);return()=>{cancelAnimationFrame(frame);window.clearInterval(interval);};},[]);const totals=useMemo(()=>{const since=start(period);const convertedJobs=jobs.filter((job)=>job.sale_converted_at&&new Date(job.sale_converted_at).getTime()>=since);const linked=new Set(convertedJobs.map((job)=>job.lead_id).filter(Boolean));const convertedLeads=leads.filter((lead)=>lead.converted_at&&new Date(lead.converted_at).getTime()>=since&&!linked.has(lead.id));const rows=[...convertedLeads.map((lead)=>({scope:lead.sale_scope||[],telus:lead.telus_sims_sold||0,koodo:lead.koodo_sims_sold||0})),...convertedJobs.map((job)=>({scope:job.lead_data?.sale_scope||[],telus:job.telus_sims_sold||0,koodo:job.koodo_sims_sold||0}))];const count=(names:string[])=>rows.filter((row)=>names.some((name)=>row.scope.includes(name))).length;return[{label:"Wi-Fi",value:count(["Fibre internet","Copper internet"])},{label:"Optik TV",value:count(["Optik TV"])},{label:"Smart Home Security",value:count(["Security"])},{label:"Home Phone",value:count(["Home phone"])},{label:"TELUS Mobility",value:rows.reduce((sum,row)=>sum+row.telus,0)},{label:"Koodo Mobility",value:rows.reduce((sum,row)=>sum+row.koodo,0)}];},[period,leads,jobs]);return <Card className="mt-6"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Product sales tracker</CardTitle><p className="mt-1 text-sm text-muted-foreground">Live product and mobility totals without duplicate linked records.</p></div><select className="h-9 rounded-md border border-input bg-background px-3 text-sm capitalize" value={period} onChange={(event)=>setPeriod(event.target.value as Period)}>{(["daily","weekly","monthly","yearly"]as Period[]).map((item)=><option key={item} value={item}>{item}</option>)}</select></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{totals.map((item)=><div key={item.label} className="rounded-lg border border-border p-4"><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-2 text-2xl font-semibold">{item.value}</p></div>)}</div></CardContent></Card>;}
